name: MyiOS CI

on:
  push:
    branches:
     - main
 
  pull_request:
      branches:
      - main


jobs:
  build:
  
   runs-on: macos-latest
   
   setup:
   -  name: Checkout Code
   -  uses: actions/checkout@v4
   
   -  name: Run SwiftLint
   -  run: swiftlint
   
   - name: Build iOS App
    run: |
        xcodebuild \
        -project MyiOSApp.xcodeproj \
        -scheme MyiOSApp \
        -sdk iphonesimulator \
        -configuration Debug \
         build
    
    - name: Test iOS App
       run: |
         xcodebuild \
         -project MyiOSAppTest.xcodeproj \
         -scheeme MyiOSApp \
         -sdk iphonesimulator \
         -destination 'platform=iOS Simulator, name=iPhone 16' \
         test
    
     - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
           name: test-results
           path: TestResult/
    
        
   

